import './globals.css'
import { Header } from '../components/Header'
import { Layout } from '../components/Layout'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Task App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Layout>
          {children}
        </Layout>
        <ToastContainer />
      </body>
    </html>
  )
}
